### PR TITLE
[RFC] std::experimental::optional as a new nullable type

### PR DESCRIPTION
**Pull request by cinghiale**
This is a first attempt to support `std::experimental::optional` as a new nullable type.

It makes possible to deserialize a json like:

```json
{
  "first_name": "Douglas",
  "last_name": null
}
```

into:

```cpp
struct Author {
  std::string first_name;
  std::experimental::optional<std::string> last_name;
}
```

This PR needs some adjustments, but I want to know if you are interested in this functionality.

Things I like to do before an, eventually, merge:

1. reduce the copy/paste code between `Handler<optional>` and `PointerHandler<T>`
2. given the experimental status of `optional` (until c++17) I'd like to move `Handler<optional>` in a different header file **not** included by default

What do you think?

### CODE REVIEW

**Comment by netheril96** [comment]
I thought about `std::optional` in the beginning, but gave up because it is too much work. For one, we need to deal with the different naming `std::experimental::optional` and `std::optional`. For two, we need the test case to compile and run even on compilers with only c++11 support. `CheckCXXCompilerFlag ` and `CheckCXXSourceCompiles` can be used to test the compiler and then conditionally enable the `optional` part.

**Comment by cinghiale** [comment]
I understand the (IMHO minor) hassle but I think that `std::optional` is a better way to express the lacks of a value instead of a pointer.

**Comment by netheril96** [comment]
The internal handler has type `std::unique_ptr<Handler<ElementType>>`, but that is only because `optional` is not always available. When `optional` is available, the type should be `std::optional<Handler<ElementType>>` to reduce indirection.

**Comment by cinghiale** [comment]
I fought the compiler for a while until I realized that an Handler<T> is a non-copyable non-movable class and thus cannot be wrapped in an optional<T>.

Why is `BaseHandler` non movable?

**Comment by netheril96** [comment]
`BaseHandler` is non movable because I don't want to implement move constructor for each subclass, as it is both error prone and time consuming.

According to http://en.cppreference.com/w/cpp/utility/optional, the only requirement for the type to be wrapped in an optional is `Destructible`, which `BaseHandler` surely conforms. Try call `emplace` instead of moving a new value into the optional.

**Comment by cinghiale** [comment]
The double `nullopt` is a spurious commit (sorry for the noise)

Good hint about `emplace`, I'll try right now

**Comment by cinghiale** [comment]
You are right, `emplace` did the trick

**Pull request merged**
